apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server-app
  labels:
    app: cloud-config-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config-server-app
  template:
    metadata:
      labels:
        app: cloud-config-server-app
    spec:
      containers:
        - name: cloud-config-server-app
          image: capmanojnew8/cloud-config-server:0.0.1
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 9296

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config-server-svc
spec:
  ports:
    - targetPort: 9296
      port: 80
  selector:
    app: cloud-config-server-app
